/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */

#ifndef ORG_GENIVI_VEHICLE_PLAYGROUNDTYPES_PLAYGROUND_TYPES_SOMEIP_DEPLOYMENT_HPP_
#define ORG_GENIVI_VEHICLE_PLAYGROUNDTYPES_PLAYGROUND_TYPES_SOMEIP_DEPLOYMENT_HPP_


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif
#include <CommonAPI/SomeIP/Deployment.hpp>
#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace org {
namespace genivi {
namespace vehicle {
namespace playgroundtypes {
namespace PlaygroundTypes_ {

// typecollection-specific deployment types
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> GearDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> DriveTypeDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> DoorsIDDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> DoorCommandDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::IntegerDeployment<uint8_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint8_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint16_t>
> GPSDateDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::IntegerDeployment<uint8_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint8_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint8_t>
> GPSTimeDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> GPSPositionDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::StructDeployment<
        CommonAPI::SomeIP::IntegerDeployment<uint8_t>,
        CommonAPI::SomeIP::IntegerDeployment<uint8_t>,
        CommonAPI::SomeIP::IntegerDeployment<uint16_t>
    >,
    CommonAPI::SomeIP::StructDeployment<
        CommonAPI::SomeIP::IntegerDeployment<uint8_t>,
        CommonAPI::SomeIP::IntegerDeployment<uint8_t>,
        CommonAPI::SomeIP::IntegerDeployment<uint8_t>
    >,
    CommonAPI::SomeIP::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment
    >
> StatusGPSDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> DoorsStatusDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    ::org::genivi::vehicle::playgroundtypes::PlaygroundTypes_::DoorCommandDeployment_t,
    ::org::genivi::vehicle::playgroundtypes::PlaygroundTypes_::DoorCommandDeployment_t,
    ::org::genivi::vehicle::playgroundtypes::PlaygroundTypes_::DoorCommandDeployment_t,
    ::org::genivi::vehicle::playgroundtypes::PlaygroundTypes_::DoorCommandDeployment_t
> CarDoorsCommandDeployment_t;


// typecollection-specific deployments

} // namespace PlaygroundTypes_
} // namespace playgroundtypes
} // namespace vehicle
} // namespace genivi
} // namespace org

#endif // ORG_GENIVI_VEHICLE_PLAYGROUNDTYPES_PLAYGROUND_TYPES_SOMEIP_DEPLOYMENT_HPP_
