/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_ORG_GENIVI_VEHICLE_PLAYGROUND_PLAYGROUND_INSTANCE_HPP_
#define V1_ORG_GENIVI_VEHICLE_PLAYGROUND_PLAYGROUND_INSTANCE_HPP_

#include <string>

namespace v1 {
namespace org {
namespace genivi {
namespace vehicle {
namespace playground {

const char * const Playground_1 = "1";

const std::string Playground_INSTANCES[] = {
    Playground_1
};

} // namespace playground
} // namespace vehicle
} // namespace genivi
} // namespace org
} // namespace v1

// Compatibility
namespace v1_0 = v1;

#endif // V1_ORG_GENIVI_VEHICLE_PLAYGROUND_PLAYGROUND_INSTANCE_HPP_
